drop trigger if exists tr_meta_type_invalidated_chunk_invalidate_type_built_flag on meta_type_invalidated_chunk;
create trigger tr_meta_type_invalidated_chunk_invalidate_type_built_flag
after insert or update or delete
on meta_type_invalidated_chunk
for each row 
execute function ${mainSchemaName}.trf_meta_type_invalidated_chunk_after_update();
